import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv(r"C:\Users\Nijil\Script by\PyProjects\PyGlobal\Universities.csv")
print(df.head())
a=np.array([1,2,3,4])
print(type(a))
print(a[2])
b=np.array([(1,2,3,4),(5,7,8,9)])
print(b)
b=b.reshape(4,2)
print(b)
print(a.sum(),a.prod(),a.min(),a.max())
print(b.sum(axis=0))
print(b.sum(axis=1))
dtfrm=pd.DataFrame({'column1':[1,2,3,2],'column2':['A','B','C','B']})
print(dtfrm)
print(dtfrm[dtfrm.duplicated()])
dt2=dtfrm.drop_duplicates() 
print(dt2)
dtfrm=pd.DataFrame({'column1':[1,2,2,4],'column2':['A','B','B','D']})
print(dtfrm)
print(dtfrm.duplicated())
print(dtfrm[dtfrm.duplicated()])
dt3=dtfrm.drop_duplicates()
print(dt3)
dt3=dt3.reset_index()
print(dt3)
dt3=dt3.drop(columns='index',axis=1)
print(dt3)
dt3=dt3.drop(index=2,axis=0)
print(dt3)
print(df.head())
df1=df.drop(df.index[[1,4]],axis=0)
print(df1)
df2=df.drop([1,2,3,4])
print(df2)

""" import warnings
warnings.filterwarnings('ignore')
plt.hist(df['SAT'])
plt.title("Histogram")
plt.xlabel('SAT Score')
plt.ylabel('Frequency   ')
plt.show()
plt.hist(df['Accept'])
plt.title('Acceptance Rate')
plt.xlabel('Acceptance')
plt.ylabel('Frequency')
plt.show()
sns.histplot(df['SAT'])
plt.show()
sns.distplot(df['Accept'])
plt.show()
plt.plot(df['SAT'],df['Accept'],'bo')
plt.xlabel('SAT')
plt.ylabel('Acceptance')
plt.show()
sns.pairplot(df)
plt.show()
sns.pairplot(df.iloc[:,1:4])
plt.show()
plt.boxplot(df['SAT'],vert=False)
plt.show() """